scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["fastapi-app:8080"]

  - job_name: "mlflow"
    static_configs:
      - targets: ["mlflow_server:5000"]

  - job_name: "mlflow_metrics"
    static_configs:
      - targets: ["mlflow_server:5001"]  # Expose custom MLflow metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]