name: Deploy FastAPI ML App

on:
  push:
    branches:
      - main  # Triggers deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mlmodel-sentimentanalysis-fastapi-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/mlmodel-sentimentanalysis-fastapi-app:latest

    - name: Deploy to EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/mlops.pem
        chmod 600 ~/.ssh/mlops.pem
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        ssh -i ~/.ssh/mlops.pem ec2-user@${{ secrets.SERVER_IP }} << 'EOF'
          # Ensure EC2 instance is updated
          sudo yum update -y
          
          # Install Docker if not installed
          if ! command -v docker &> /dev/null; then
            sudo yum install -y docker
            sudo systemctl start docker
            sudo usermod -aG docker ec2-user
          fi
          
          # Ensure Docker is running
          sudo systemctl enable docker
          sudo systemctl start docker

          # Ensure user has Docker access
          newgrp docker

          # Deploy FastAPI App (Updated Image Name)
          docker pull ${{ secrets.DOCKER_USERNAME }}/mlmodel-sentimentanalysis-fastapi-app:latest
          docker stop fastapi-container || true
          docker rm fastapi-container || true
          docker run -d -p 80:8080 --restart=always --name fastapi-container ${{ secrets.DOCKER_USERNAME }}/mlmodel-sentimentanalysis-fastapi-app:latest

          # Deploy Grafana
          docker stop grafana_server || true
          docker rm grafana_server || true
          docker run -d -p 3001:3000 --restart=always --name grafana_server grafana/grafana

          # Deploy MLflow (Check Image Source)
          docker stop mlflow_server || true
          docker rm mlflow_server || true
          docker run -d -p 5000:5000 --restart=always --name mlflow_server ghcr.io/mlflow/mlflow:v2.5.0

          # Deploy Prometheus
          docker stop prometheus_server || true
          docker rm prometheus_server || true
          docker run -d -p 9090:9090 --restart=always --name prometheus_server prom/prometheus
        EOF
