name: Deploy FastAPI ML App

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mlmodel-sentimentanalysis-fastapi-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/mlmodel-sentimentanalysis-fastapi-app:latest

    - name: Deploy to EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/mlops.pem
        chmod 600 ~/.ssh/mlops.pem
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

        # Copy Prometheus config to EC2
        echo "Copying prometheus.yml to EC2..."
        scp -i ~/.ssh/mlops.pem prometheus.yml ec2-user@${{ secrets.SERVER_IP }}:/home/ec2-user/prometheus.yml

        # Connect to EC2 and perform deployment
        ssh -i ~/.ssh/mlops.pem ec2-user@${{ secrets.SERVER_IP }} << 'EOF'
          echo "Updating EC2 instance..."
          sudo yum update -y
          
          # Ensure Docker is installed and running
          if ! command -v docker &> /dev/null; then
            echo "Installing Docker..."
            sudo yum install -y docker
            sudo systemctl start docker
            sudo usermod -aG docker ec2-user
            sudo systemctl enable docker
          else
            echo "Docker already installed."
          fi

          # Restart Docker if necessary
          sudo systemctl restart docker
          echo "Docker service started."

          # Pull and deploy FastAPI container
          echo "Deploying FastAPI App..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/mlmodel-sentimentanalysis-fastapi-app:latest
          docker stop fastapi-container || true
          docker rm fastapi-container || true
          docker run -d -p 80:8080 --restart=always --name fastapi-container ${{ secrets.DOCKER_USERNAME }}/mlmodel-sentimentanalysis-fastapi-app:latest

          # Deploy Grafana
          echo "Deploying Grafana..."
          docker stop grafana_server || true
          docker rm grafana_server || true
          docker run -d -p 3001:3000 --restart=always --name grafana_server grafana/grafana

          # Deploy MLflow
          echo "Deploying MLflow..."
          docker stop mlflow_server || true
          docker rm mlflow_server || true
          docker run -d -p 5000:5000 --restart=always --name mlflow_server ghcr.io/mlflow/mlflow:v2.5.0

          # Deploy Prometheus
          echo "Deploying Prometheus..."
          docker stop prometheus_server || true
          docker rm prometheus_server || true
          docker run -d -p 9090:9090 --restart=always --name prometheus_server prom/prometheus

          # Copy Prometheus config to container
          echo "Copying prometheus.yml to Prometheus container..."
          docker cp /home/ec2-user/prometheus.yml prometheus_server:/etc/prometheus/prometheus.yml
          
          # Restart Prometheus with updated config
          echo "Restarting Prometheus with new config..."
          docker restart prometheus_server

          echo "Deployment completed successfully!"
        EOF
